//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBConfig
    {
        public int Id { get; set; }
        public Nullable<int> Store_Id { get; set; }
        public string CompanyFilePath { get; set; }
        public string QBVersion { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string QBYear { get; set; }
        public string BillAccListID { get; set; }
        public string BillAccName { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
