//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteConfiguration
    {
        public int id { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> Currencydigit { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> CategoryLarge { get; set; }
        public Nullable<int> CategoryMedium { get; set; }
        public Nullable<int> CategorySmall { get; set; }
        public Nullable<int> ProductLarge { get; set; }
        public Nullable<int> ProductMedium { get; set; }
        public Nullable<int> ProductSmall { get; set; }
    }
}
