//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesGeneralEntriesHistory
    {
        public int id { get; set; }
        public Nullable<int> storeid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> salesdate { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> syncstatus { get; set; }
        public Nullable<decimal> totalamount { get; set; }
    }
}
