//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_otherdeposit
    {
        public int id { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> storeid { get; set; }
        public string name { get; set; }
        public string paymentmethod { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string options { get; set; }
        public string Vendor { get; set; }
        public string Other { get; set; }
    }
}
