//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExcelRead
    {
        public int id { get; set; }
        public Nullable<bool> IsFlag { get; set; }
        public Nullable<System.DateTime> Excelreadate { get; set; }
        public string Filename { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
