//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChildSalesEntries
    {
        public int id { get; set; }
        public Nullable<int> Gid { get; set; }
        public Nullable<int> storeid { get; set; }
        public string Groupname { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Title { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Typeid { get; set; }
    }
}
