//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Excelread_Errormsg
    {
        public int id { get; set; }
        public Nullable<int> Excelid { get; set; }
        public Nullable<int> RowNo { get; set; }
        public Nullable<int> ColumnNo { get; set; }
        public string ErrorMessage { get; set; }
    }
}
