//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwrootBL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_store
    {
        public int id { get; set; }
        public Nullable<int> Storeid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> Reg_userid { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string RoleName { get; set; }
    }
}
